name: My Library Project CI Build

# Listen on *any* push or PR (no branch filter)
on:
  push: {}
  pull_request: {}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn -B clean test --file pom.xml

      - name: Upload Surefire Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-${{ github.run_id }}
          path: target/surefire-reports/
