name: Maven CI

# Trigger this workflow on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up JDK 11 (matches your pom.xml’s <maven.compiler.source>11)
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      # 3) Cache Maven dependencies (optional but speeds up builds)
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4) Run Maven clean + tests
      - name: Build and run tests
        run: mvn --batch-mode clean test
